### ISSUE TITLE
change "API token" button to provide token, not form to request

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-astrooda#1]

**Comment by volodymyrss** [comment]
ideally, move the button towards right top corner

**Comment by volodymyrss** [comment]
ideally, let's have both placements of the API token button: top right

**Comment by volodymyrss** [comment]
we could also make a pop-up on API code button

**Comment by volodymyrss** [comment]
It could also send an email to user with token.

**Comment by burnout87** [comment]
I would also add a small instruction on how to use that token within the API code

**Comment by volodymyrss** [comment]
![image](https://user-images.githubusercontent.com/3909535/120191589-6850dc00-c21a-11eb-9544-720f357e36fb.png)

**Comment by volodymyrss** [comment]
@ferrigno  notes:

> Either the API token tab gives the token or it should disappear.
> 
> While writing the user guide, I realize that it is too confusing to have this tab present and popping up an email form. Either it gives the token (if you are logged in) or it prompts a window inviting to login to get a token.
> 
> If too long to develop this feature, let's suppress this tab.

**Comment by motame** [comment]
As suggested by Carlo the API token buttom does appear only in the main toolbar (at the top of the page).
Once pushed, a window is displayed allowing the user to see the token, copy it or send to himself by email.
