### ISSUE TITLE
T1, T2 are not used in Antares, thus misleading and should be hidden

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/frontend-astrooda#10]

**Comment by volodymyrss** [comment]
you mean those on top?

**Comment by dsavchenko** [comment]
Yes. Antares backend now only can calculate upper limits throughout all time span of the data.
And I realise this change may not be trivial, as these fields are common for every instrument. 
On the dispatcher level, this is also the case, BTW

**Comment by volodymyrss** [comment]
Yes. But at least plugin can return detailed error if invalid range is requested. It's slightly less interactive but still useful.

**Comment by dsavchenko** [comment]
I don't think that an error should be returned, but better some warning about parameters are not used at all.
Is there a place in the dispatcher response schema for such kind of messages?

**Comment by motame** [comment]
You mean when the ANTARES tab is active T1 and T2 should be hidden ? and show them back when the user moves to another tab ...

**Comment by dsavchenko** [comment]
> You mean when the ANTARES tab is active T1 and T2 should be hidden ? and show them back when the user moves to another tab ...

Yes, this is an original idea

**Comment by volodymyrss** [comment]
I am not sure it is suitable. Let's discuss today!

**Comment by dsavchenko** [comment]
Alternatively, the fields may be fixed to the time span from January 2007 to December 2017, because that's what data release covers. But yes, let's discuss on the meeting

**Comment by volodymyrss** [comment]
it's true that the default T1,T2 is not ideal for ANTARES. You could configure it on deployment.
I added to the agenda. At the end, but it's not to say that it is the smallest item.
