### ISSUE TITLE
Warning about help pages for the new modules

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/frontend-astrooda#110]
For new modules (see #109) there are warnings of the form 
```
Notice: Undefined index: help_page_nids in astrooda_main_block_content() (line 289 of /var/www/astrooda/sites/all/modules/astrooda/astrooda.module).
```
in frontend.

PS: I didn't perform any action on the module's help pages.

**Comment by motame** [comment]
This means that there is an inconsistency between the DB content and the version of the module: an old DB content with an up-to-date version of the module. Some variables introduced by the module are missing in the database.
To fix this issue, there are two options :
- Re-install the module :
   drush dis -y astrooda
   drush pmu -y astrooda
   drush en -y astrooda
- Use the latest DB content :
https://github.com/oda-hub/frontend-drupal7-db-for-astrooda

**Comment by volodymyrss** [comment]
It is because @dsavchenko added a new instrument. It is not clear if it should react like that. @motame offers to investigate more!

**Comment by motame** [comment]
Indeed, an instrument module may not have help page(s).
Fixed ! pushed in gitlab.

**Comment by volodymyrss** [comment]
I note that the mirror required token update. 

it's here now:

https://github.com/oda-hub/frontend-astrooda/commit/d0bc412522f8bbd1b2912f829c9e1f84ee35c945
