### ISSUE TITLE
if "selected_catalog=" occurs in the parameter URL list, the request does not start

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-astrooda#119]
e.g. this comes from default:

`https://www.astro.unige.ch/mmoda/?DEC=-29.74516667&E1_keV=20&E2_keV=40&RA=265.97845833&T1=2017-03-06T13%3A26%3A48.0&T2=2017-03-06T15%3A32%3A27.0&T_format=isot&detection_threshold=7&image_scale_max=&image_scale_min=&instrument=isgri&integral_data_rights=public&max_pointings=50&osa_version=OSA11.1&product_type=isgri_image&query_status=new&query_type=Real&radius=15&selected_catalog=&src_name=1E+1740.7-2942`

this works (removing `selected_catalog=`):

`https://www.astro.unige.ch/mmoda/?DEC=-29.74516667&E1_keV=20&E2_keV=40&RA=265.97845833&T1=2017-03-06T13%3A26%3A48.0&T2=2017-03-06T15%3A32%3A27.0&T_format=isot&detection_threshold=7&image_scale_max=&image_scale_min=&instrument=isgri&integral_data_rights=public&max_pointings=50&osa_version=OSA11.1&product_type=isgri_image&query_status=new&query_type=Real&radius=15&src_name=1E+1740.7-2942`

**Comment by motame** [comment]
Indeed ! when the field is empty, the request was failing.
Fixed at present and pushed in GitHub.
Can be closed !

**Comment by volodymyrss** [comment]
Awesome, thanks @motame !
