### ISSUE TITLE
add a button in frontend to open in renku

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-astrooda#129]

**Comment by burnout87** [comment]
Started the implementation:

![image](https://user-images.githubusercontent.com/3757833/154112544-114c571f-63e5-49b5-88d4-38a5039332ab.png)

**Comment by burnout87** [comment]
Output to optimize (css and all the rest), but getting there...

![image](https://user-images.githubusercontent.com/3757833/154145450-ec55b1b9-33ee-4b29-a43a-ebecf2ad0859.png)

**Comment by burnout87** [comment]
Improved
![image](https://user-images.githubusercontent.com/3757833/154240005-4693c693-7948-4244-aebe-dbb6a8d8b1ac.png)

I will have now to fix a couple of minor things on the dispatcher, to avoid to encounter certain situations

**Comment by volodymyrss** [comment]
Cool! 

The button should be more like the "Run API code on Renku".
And, ideally we'd want the button to directly open a new page. 

If not easy, we could keep it as it is, and rename "Renku publish result" to  "ODA API code is published! Click here to start renku session with your API code"

**Comment by burnout87** [comment]
> The button should be more like the "Run API code on Renku". And, ideally we'd want the button to directly open a new page.
>

Ok! It should be relatively easy .

> 
> edit: also, beware not to publish API code with token in public repository. The repository will be public, so the token should be removed, maybe replaced with some "input()".

Ok, the dispatcher has to take care of removing it then

**Comment by burnout87** [comment]
It opens now the returned link in a new tab. In addition, I added a progress bar to be displayed while waiting for the request to complete

![image](https://user-images.githubusercontent.com/3757833/154296296-818d359b-13ff-4372-9793-a0dedb8b6bee.png)

**Comment by burnout87** [comment]
https://gitlab.astro.unige.ch/oda/frontend/astrooda/-/merge_requests/84

**Comment by burnout87** [comment]
If  nothing else is missing I would merge it

**Comment by volodymyrss** [comment]
merged hence closing
