### ISSUE TITLE
make larger button for contact and login

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-astrooda#16]

**Comment by volodymyrss** [comment]
"Resolve" is normal, right? I would go for normal.
Maybe also @burnout87 @ferrigno @andriineronov  can comment.

**Comment by burnout87** [comment]
I think "Normal" is the proper size, but I would also consider (perhaps something to think about in the future) adding a small label that explains the functionality of the button. Just the icon might not be sufficient.

**Comment by motame** [comment]
That's my choice too and I did not want to influence from the beginning ;-)

**Comment by volodymyrss** [comment]
So we could consider labels, if there is a suggestion what should they say and where they would be.

To preview, @burnout87 you can edit html/css with page inspector and maybe send a screenshot?

Like here:

![image](https://user-images.githubusercontent.com/3909535/119640776-3c4bea00-be19-11eb-93fa-0621214bacc6.png)

**Comment by motame** [comment]
By the way we do have the tips when hovering on the buttons showing the function of the button: "Contact Us", "Sign in" and "Help"

**Comment by volodymyrss** [comment]
Tips are good, but the concern was how to direct user to those buttons when user would want to use them - i.e. in a need of contact.
Labels could attract, but maybe it's too much, for me anyway, it's a perception thing.
Or maybe we could change colors.

Here is an overly colorized variant:

![image](https://user-images.githubusercontent.com/3909535/119642267-d2ccdb00-be1a-11eb-8084-632bffe07662.png)

**Comment by motame** [comment]
With labels:
![astrooda-buttons-labels-01](https://user-images.githubusercontent.com/44972498/119642331-e5471480-be1a-11eb-8d4e-7bf0957d997d.jpg)

**Comment by burnout87** [comment]
> With labels:
> ![astrooda-buttons-labels-01](https://user-images.githubusercontent.com/44972498/119642331-e5471480-be1a-11eb-8d4e-7bf0957d997d.jpg)

Might not be the prettiest, but I think it is more clear the available functionalities

**Comment by volodymyrss** [comment]
> > With labels:
> > ![astrooda-buttons-labels-01](https://user-images.githubusercontent.com/44972498/119642331-e5471480-be1a-11eb-8d4e-7bf0957d997d.jpg)
> 
> Might not be the prettiest, but I think it is more clear the available functionalities

Let's see what @ferrigno or maybe even @andriineronov  say.

**Comment by motame** [comment]
Another option would be to show them for let say 3 seconds then hide them by sliding left or right :-)

**Comment by volodymyrss** [comment]
> Another option would be to show them for let say 3 seconds then hide them by sliding left or right :-)

oh, can you should how would this look like?

**Comment by burnout87** [comment]
Perhaps with some border
<img width="1407" alt="Screenshot 2021-05-26 at 12 14 13" src="https://user-images.githubusercontent.com/3757833/119643398-f93f4600-be1b-11eb-9953-2a148e5798cc.png">

Another option with a drop-down menu ?

**Comment by volodymyrss** [comment]
Border here does separation but not so much esthetics. I am not sure how dropdown would look. Will it not conceal then from the user? If there is an option we can also show it to @ferrigno  and @andriineronov .

**Comment by motame** [comment]
> 
> 
> > Another option would be to show them for let say 3 seconds then hide them by sliding left or right :-)
> 
> oh, can you should how would this look like?

You can try it:
http://cdcidev.mtmco.net/cdci/astrooda/

**Comment by motame** [comment]
> 
> 
> Perhaps with some border
> <img alt="Screenshot 2021-05-26 at 12 14 13" width="1407" src="https://user-images.githubusercontent.com/3757833/119643398-f93f4600-be1b-11eb-9953-2a148e5798cc.png">
> 
> Another option with a drop-down menu ?

 If if it not opened user may miss the information that 3  functions are there...

**Comment by motame** [comment]
I added the hover feature. On hover of the toolbar the labels are shown

**Comment by volodymyrss** [comment]
> I added the hover feature. On hover of the toolbar the labels are shown

Currently they also shrink-modify the whole bar thickness and also the expanding effect seems a bit unpredictable and pulsates! :)

**Comment by burnout87** [comment]
> > I added the hover feature. On hover of the toolbar the labels are shown
> 
> Currently they also shrink-modify the whole bar thickness and also the expanding effect seems a bit unpredictable and pulsates! :)

Yeah I experienced the same. Perhaps the CSS needs some adjustment. In any case, I like the idea.

**Comment by motame** [comment]
Indeed yes, I should have a look into the css.

**Comment by ferrigno** [comment]
I like the version with label and without border. I would avoid fancy effects that could lead to a loss of time in debugging.

**Comment by motame** [comment]
Actually the expanding is done properly on my browsers (Firefox and Chrome) expand on hover then hide labels once outside but there is definitely an issue with the height of the toolbar which is  changing only during the expanding and the inverse.

**Comment by volodymyrss** [comment]
> Actually the expanding is done properly on my browsers (Firefox and Chrome) expand on hover then hide labels once outside but there is definitely an issue with the height of the toolbar which is changing only during the expanding and the inverse.

for me, on firefox  88.0.1, it expands-contrats multiple times. Let's just keep then with labels, it's not that important.

**Comment by burnout87** [comment]
I tested on Chromium 90.0.4430.212

**Comment by motame** [comment]
Let us stick to the version with permanent labels for the time being.

**Comment by motame** [comment]
The final choice of the normal size has been implemented.
