### ISSUE TITLE
Update ignored parameters

### ISSUE THREAD

**Issue by burnout87** [oda-hub/frontend-astrooda#19]
The list of ignored parameters used to generate the product url (within `get_query_url`) needs to be updated according to the way the dispatcher-app generates it.

https://github.com/oda-hub/frontend-astrooda/blob/86b9874b1a2d927f9dbf25c940e46ee7f26adfe1/js/astrooda.instrument.js#L60

Within the dispatcher-app the fields are ignored before the moment the url is created:

[https://github.com/oda-hub/dispatcher-app/blob/d82143fdc510f0b7793cb1755013666bf45e4330/cdci_data_analysis/flask_app/dispatcher_query.py#L602-L609](https://github.com/oda-hub/dispatcher-app/blob/d82143fdc510f0b7793cb1755013666bf45e4330/cdci_data_analysis/flask_app/dispatcher_query.py#L602-L609)

**Comment by volodymyrss** [comment]
is this done @burnout87 ?

**Comment by burnout87** [comment]
Yes, I'll close it
