### ISSUE TITLE
Hide Drupal database user password in the file settings.php

### ISSUE THREAD

**Issue by motame** [oda-hub/frontend-astrooda#23]
The file settings.php found in sites/default/settings.php may undergo changes and need to be kept under control in github.
However it does contain a critical information: the database user password ! which is not desirable in github.

**Comment by volodymyrss** [comment]
template added there https://github.com/oda-hub/frontend-drupal7-for-astrooda/pulls
described here: https://github.com/oda-hub/frontend-chart/blob/master/README.md
