### ISSUE TITLE
After submitting a query the progress window does not appear

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/frontend-astrooda#26]
I asked for an image in a time range.
The submit button changed color and became non clickable.
No requests to open pop ups or wahtsover 
(I am a on the obs VPN)

![screenshot-frontend staging odahub io-2021 05 20-02_04_43](https://user-images.githubusercontent.com/2527219/118899785-d4287000-b90f-11eb-9152-f99c33ca1e12.png)

Firefox 88.0.1 on Linux

**Comment by motame** [comment]
Volodymyr,
I can also investigate if you wish to ?

**Comment by volodymyrss** [comment]
Thanks Mohamed, yes please!
It seems like ANTARES validation somehow applies to ISGRI and JEMX. Setting 1deg radius, for example, does not cause the problem.

**Comment by motame** [comment]
OK !

**Comment by dsavchenko** [comment]
> It seems like ANTARES validation somehow applies to ISGRI and JEMX.

Indeed. My uneducated guess is that it is due to data-bv-field="radius" in all these fields.
This attribute is populated by drupal when rendering form. Could it be tweaked?

**Comment by volodymyrss** [comment]
> > It seems like ANTARES validation somehow applies to ISGRI and JEMX.
> 
> Indeed. My uneducated guess is that it is due to data-bv-field="radius" in all these fields.
> This attribute is populated by drupal when rendering form. Could it be tweaked?

yeah, I would make a simple adjustment by renaming this field name. It is different radius after all, very different meaning. But I thought this difference would be reflected in it being nested. 
But Mohamed can provide the  right guidance.

**Comment by dsavchenko** [comment]
> I would make a simple adjustment by renaming this field name.

But this way Antares processing will break, as the dispatcher expect "radius" field

I can, of course, change it in the plugin. Because the meaning is different, you are right.

**Comment by volodymyrss** [comment]
I would let @motame investige as he kindly offered, and in case it's not too easy, change the name in both the plugin and frontend.

**Comment by motame** [comment]
It's really a tricky issue !
It should be a bug in the Boostrap Validation JS lib.
We do have one form per instrument for the parameters and the form ids and names are distinct.
The expected behavior for the validator is to consider validation parameters (data-****) per input name and form.


Different forms may have the same input names. In our case : for the radius name="radius" 
However, the noticed behavior is that all inputs with the same name (even in different forms) are validated !!!
To overcome that I had to make distinct the radius input name. It become : name = $form_id.'radius'
Example: name="astrooda_antares_radius" for Antares and name="astrooda_isgri_radius" for ISGRI, etc.

Fixed then and pushed to reference.

**Comment by motame** [comment]
Volodymyr,
After the fix, I see that no image is retrured for JEMX with the default values (just pushing submit !).
Would you please have a look?

[http://cdcidev.mtmco.net/cdci/astrooda/](http://cdcidev.mtmco.net/cdci/astrooda/)

**Comment by volodymyrss** [comment]
> Volodymyr,
> After the fix, I see that no image is returned for JEMX with the default values (just pushing submit !).
> Would you please have a look?
> 
> http://cdcidev.mtmco.net/cdci/astrooda/

I too noticed it before, and made an issue https://github.com/oda-hub/dispatcher-plugin-integral/issues/24.
But choosing different set works.
I am not sure what changed, analysis seems correct. Default parameters must have changed.

**Comment by volodymyrss** [comment]
> It's really a tricky issue !
> It should be a bug in the Boostrap Validation JS lib.
> We do have one form per instrument for the parameters and the form ids and names are distinct.
> The expected behavior for the validator is to consider validation parameters (data-****) per input name and form.
> 
> Different forms may have the same input names. In our case : for the radius name="radius"
> However, the noticed behavior is that all inputs with the same name (even in different forms) are validated !!!
> To overcome that I had to make distinct the radius input name. It become : name = $form_id.'radius'
> Example: name="astrooda_antares_radius" for Antares and name="astrooda_isgri_radius" for ISGRI, etc.
> 
> Fixed then and pushed to reference.

Thanks! All seems good now.
