### ISSUE TITLE
add notice in progress modal that request can be closed and re-sent

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-astrooda#31]

**Comment by burnout87** [comment]
What do you think of the following message and position @motame @volodymyrss @ferrigno ?

![Screenshot from 2021-06-10 16-43-22](https://user-images.githubusercontent.com/3757833/121545683-0575f680-ca0b-11eb-93cc-e4929edf0ea4.png)

**Comment by volodymyrss** [comment]
I would even say something like "please note that you may close this window and repeat the same request at later time to check the request progress. You may also follow the link we received in the email."

Or shorter but with similar level of detail.

Also, reference to email could be supported - dispatcher does inform of email submission.
Would be nice to also have the products url here by the way.
Maybe later, these points may take some development.

**Comment by burnout87** [comment]
The message is hidden when request is complete (`done` status)

![image](https://user-images.githubusercontent.com/3757833/121556536-432b4d00-ca14-11eb-925f-cbf837978e50.png)

**Comment by volodymyrss** [comment]
Ok! Just "we received" not quite right, since it is them who received.

**Comment by volodymyrss** [comment]
I'd really invite @ferrigno to review.

**Comment by burnout87** [comment]
> Ok! Just "we received" not quite right, since it is them who received.

Ops! Noticed :D

**Comment by burnout87** [comment]
![image](https://user-images.githubusercontent.com/3757833/121600296-8ef5ea80-ca44-11eb-9968-10fcbdc4a140.png)

**Comment by ferrigno** [comment]
What is the request comes from somebody not logged in?
In either  case
1. I find the button "cancel" confusing, I wolud prefer "Close this window" or "Close".
I suggest a slight improvement on your already excellent text:
1.  "You can close this window and resubmit the same request at a later time to check its status or retrieve results. This can be equally achieved by clicking on the link received by email. You will receive a notification at job completion"

**Comment by burnout87** [comment]
> What is the request comes from somebody not logged in?
In that case the part of the message "You may also follow the link in the email" is not displayed.

> In either case
> 
>     1. I find the button "cancel" confusing, I wolud prefer "Close this window" or "Close".
If we all agree, I will change it

>        I suggest a slight improvement on your already excellent text:
> 
>     2. "You can close this window and resubmit the same request at a later time to check its status or retrieve results. This can be equally achieved by clicking on the link received by email. You will receive a notification at job completion"

Ok! With notification I guess that you mean the email?

**Comment by burnout87** [comment]
![image](https://user-images.githubusercontent.com/3757833/121651687-2f76f980-ca9b-11eb-9ae4-5527c9662673.png)

**Comment by motame** [comment]
![oda-can-close-01](https://user-images.githubusercontent.com/44972498/121655801-2be57180-ca9f-11eb-88aa-02c9e921aa80.jpg)
The text seems to be truncated and it appears only in the first request.
It does not appear in the subsequent ones.

**Comment by burnout87** [comment]
CSS adjusted now (hopefully)

![image](https://user-images.githubusercontent.com/3757833/121657370-a498fd80-caa0-11eb-9566-f6631db70b59.png)

**Comment by ferrigno** [comment]
OK for me.

**Comment by burnout87** [comment]
It's there, if also @motame confirms it's working we can close this

**Comment by volodymyrss** [comment]
where?

**Comment by burnout87** [comment]
I mean the change has been pushed

**Comment by volodymyrss** [comment]
With no PR? Could you reference a commit (s?), for future reference?

**Comment by motame** [comment]
The modal window is used for other stuff like the help page, API token copy, etc.
I'll fix that first and comeback to you.

**Comment by volodymyrss** [comment]
Especially since the change is not yet coordinated with @motame  it's really useful to make a PR and let it be approved before merging on master.

**Comment by volodymyrss** [comment]
Here is what currently deployed master shows:

![image](https://user-images.githubusercontent.com/3909535/121673774-8e476d80-cab1-11eb-8bed-1e24a5b59c24.png)

**Comment by burnout87** [comment]
Ok I see the mistake, Will provide a fix with a next PR
