### ISSUE TITLE
Custom science window fails check

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/frontend-astrooda#35]
This should be a valid scw list
236100030010.000,236100040010.000,236100050010.000
but it is not accepted, why?
![image](https://user-images.githubusercontent.com/2527219/120814007-bc2b3000-c54e-11eb-8e30-62d73e80e83f.png)

**Comment by volodymyrss** [comment]
I suspect public frontend used not to allow NRT, since some time. We should change it back to allow this.

**Comment by volodymyrss** [comment]
in general ".00[0-9]" should be allowed
