### ISSUE TITLE
Not possible to delete inline catalog?

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/frontend-astrooda#36]
I made this request
https://frontend.staging.odahub.io/cdci/astrooda/?src_name=4U+1700-377&RA=270.80&DEC=-29.80&T1=2021-05-01&T2=2021-05-05&T_format=isot&instrument=jemx&osa_version=OSA11.0&radius=4&use_scws=no&max_pointings=50&integral_data_rights=all-private&jemx_num=1&E1_keV=3&E2_keV=20&query_type=Real&detection_threshold=5&product_type=jemx_image&query_status=new
then I clicked on catalog, click on use catalog, but finally, I am unable to remove it as inline catalog. In principle, it should be possible by clicking on the cross at the right of of "inline catalog".
![image](https://user-images.githubusercontent.com/2527219/120825106-57290780-c559-11eb-851d-22df79a2affa.png)

**Comment by motame** [comment]
Can not reproduce on my dev instance : 
http://cdcidev.mtmco.net/cdci/astrooda
Hereafter the steps of my test:
- Request ISGRI image
- Open catalogue and click on "Use catalogue"
- Request again an image
- Check that the catalogue is sent and it does 
- Click  on the cross at the right of of "inline catalog": the catalogue has been removed !
- Request again an image to ensure that the catalogue is no more sent and it is OK, not in request parameters

**Comment by ferrigno** [comment]
I used this url:
https://frontend.staging.odahub.io/cdci/astrooda/?DEC=-24.745833&E1_keV=3&E2_keV=20&RA=263.007917&T1=2020-02-15&T2=2020-02-20&T_format=isot&detection_threshold=5&instrument=jemx&integral_data_rights=public&jemx_num=1&max_pointings=5&osa_version=OSA11.0&product_type=jemx_image&query_status=new&query_type=Real&radius=4&src_name=GX+1%2B4&use_scws=no

Visualized catalog and clicked on "Use Catalog", then clicked on spectrum and submitted.
![image](https://user-images.githubusercontent.com/2527219/122220219-6b052f80-ceb0-11eb-92f5-3c3be876e512.png)

Then, I tried to click on the cross next to "inline catalog" to delete it and I did not manage. (Verified also submitting another spectrum instance)

**Comment by ferrigno** [comment]
(I removed myself as assignee, but I will follow, no worries)

**Comment by ferrigno** [comment]
According to https://github.com/oda-hub/doc-review-guidelines we agreed on using this instance for testing
https://frontend.staging.odahub.io/cdci/astrooda/

**Comment by ferrigno** [comment]
Actually the same happens also on your development instance. I cannot click on the cross next to "Inline catalog" and remove it.
Use the following link:

http://cdcidev.mtmco.net/cdci/astrooda/dispatch-data/resolve-job-url?job_id=942721d3e60f5391&session_id=X22WPD46J041WREQ&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkNhcmxvLkZlcnJpZ25vQHVuaWdlLmNoIiwibmFtZSI6ImNmZXJyaWdubyIsInJvbGVzIjoiYXV0aGVudGljYXRlZCB1c2VyLCBhZG1pbmlzdHJhdG9yLCBjb250ZW50IG1hbmFnZXIsIGdlbmVyYWwsIGludGVncmFsLXByaXZhdGUtcWxhLCBtYWdpYywgdW5pZ2UtaHBjLWZ1bGwsIHB1YmxpYy1wb29sLWhwYywgYW50YXJlcywgc2RzcyIsImV4cCI6MTYyMzkzMjQ0M30.g5-UJAlZg9y2KNr8asuZ3Okc-Ock_zdKOVVQiCSFjh8

**Comment by ferrigno** [comment]
(I use Chrome for Linux Version 91.0.4472.101 (Official Build) (64-bit)

**Comment by motame** [comment]
I finally succeed to reproduce it on my dev instance.
Indeed, the inline catalogue can be closed in the first instrument only (first tab), ISGRI, but not in the rest of instruments.
It has been fixed and pushed in gitlab.
