### ISSUE TITLE
Once you edit a source only that one is used as inline catalog

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/frontend-astrooda#37]
https://frontend.staging.odahub.io/cdci/astrooda/?src_name=4U+1700-377&RA=270.80&DEC=-29.80&T1=2021-05-01&T2=2021-05-05&T_format=isot&instrument=jemx&osa_version=OSA11.0&radius=4&use_scws=no&max_pointings=50&integral_data_rights=all-private&jemx_num=1&E1_keV=3&E2_keV=20&query_type=Real&detection_threshold=5&product_type=jemx_image&query_status=new

I look at the catalog, I edited a source to set flag=1
![catalog-jemx](https://user-images.githubusercontent.com/2527219/120825555-cbfc4180-c559-11eb-995e-84fbf96dfe39.png)
![edit-source](https://user-images.githubusercontent.com/2527219/120825593-d3234f80-c559-11eb-8fbf-238e2a990cba.png)

bu the inline catalog contains only that source afterwards !!
![image](https://user-images.githubusercontent.com/2527219/120825639-df0f1180-c559-11eb-81a1-9aaef1d2e344.png)

**Comment by ferrigno** [comment]
Thsi cannot be a "KNOWN ISSUE" as it blocks a correct analysis. It needs to be solved.

**Comment by burnout87** [comment]
I am looking into it, and discuss also with @motame

**Comment by ferrigno** [comment]
I realized that this happens only if you keep the source selected after you edit it !! 
If you unselect the source, the full catalog is used. 
I think this is unwanted, but not blocking.

**Comment by burnout87** [comment]
Still, I think that once the edit is complete, thr full list should be visualized, unless I misunderstood the workflow

**Comment by ferrigno** [comment]
The list is visualized, but the source remains selected. If you click on "use catalog" with one source selected, only that one is used. It will cause several errors by the users, but it cannot be a stopper for release.

**Comment by burnout87** [comment]
This was discussed, and decided thew current behavior is now ok.

If confirmed, we can close it.

**Comment by volodymyrss** [comment]
I've been using it for some time, seems ok!
