### ISSUE TITLE
Review defaults

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/frontend-astrooda#44]
It is a very fast and highly rewarding fix for usability. I noticed that on
https://frontend.staging.odahub.io/cdci/astrooda/
the modification that we made with Mohamed on th default 4 deg radius for JEM-X was not propagated

1. Put OSA11.0 as default
2. put 25 keV as E1_keV in ISGRI
3. put 4 deg as default radius for JEM-X
4. put 20 keV as E2_KeV in JEM-X

**Comment by burnout87** [comment]
Probably it is not yet deployed, but it's in the code. 

I will apply also the other changes.

**Comment by burnout87** [comment]
Default values are now there

**Comment by volodymyrss** [comment]
> It is a very fast and highly rewarding fix for usability. I noticed that on
> https://frontend.staging.odahub.io/cdci/astrooda/
> the modification that we made with Mohamed on th default 4 deg radius for JEM-X was not propagated
> 
>     1. Put OSA11.0 as default
> 
>     2. put 25 keV as E1_keV in ISGRI
> 
>     3. put 4 deg as default radius for JEM-X

This change results in no ScW for JEM-X in default request. I.e. user opening the page first time, choosing JEMX, and clicking submit gets an error.

That's not good.

The defaults should be changed.
 
>     4. put 20 keV as E2_KeV in JEM-X

**Comment by motame** [comment]
The instrument default values are defined in the file module_name.install.
For instance, ISGRI parameter default values of the module Astrooda_ISGRI are defined in astrooda_isgri.install
**This file is run only one time: at installation** and the default values are saved in the database at that time.
Any change after the installation is then not taken into account.
To make changes take effect a re-installation of the module is necessary and not only disabling/enabling the module.
Example:
```
drush dis -y astrooda_isgri
drush pmu -y astrooda_isgri
drush en -y astrooda_isgri
```
We can have an administration/configuration page for each instrument to update its default values and other parameters.
The requested changes in this issue have been done.
I close this issue and open a new issue to discuss and decide about the implementation of such page in instrument modules.

**Comment by volodymyrss** [comment]
oh, sorry, for this issue we meant to actually select and set new default values. Let's keep it open for  now, or we can create a new one?

**Comment by motame** [comment]
> This change results in no ScW for JEM-X in default request. I.e. user opening the page first time, choosing JEMX, and clicking submit gets an error.
> 
> That's not good.
> 
> The defaults should be changed.
> 
> > ```
> > 4. put 20 keV as E2_KeV in JEM-X
> > ```

Ah yes sorry ! it's not finished according to your comment.
I'll do the change ...

**Comment by volodymyrss** [comment]
> > This change results in no ScW for JEM-X in default request. I.e. user opening the page first time, choosing JEMX, and clicking submit gets an error.
> > That's not good.
> > The defaults should be changed.
> > > ```
> > > 4. put 20 keV as E2_KeV in JEM-X
> > > ```
> 
> Ah yes sorry ! it's not finished according to your comment.
> I'll do the change ...

There is a complexity here which we discussed in https://github.com/oda-hub/meetings/blob/main/2021-07-08/minutes.md
Basically we need to cautiously choose new defaults, and we did not choose them yet. So it's up to us.
What is set currently is ok I guess, but not ideal.

**Comment by motame** [comment]
:+1:

**Comment by ferrigno** [comment]
The polar GRB170309A is well detected in SPI-ACS while INTEGRAL points to the Galactic center

start_time='2017-03-06 13:26:54'
end_time='2017-03-06 15:02:33'
source='GRO J1719-24'

provides an ISGRI mage with two sources
of which only 
GRO J1719-24 | 74.5935 | 259.8986 | -25.0186 
seems bright

**Comment by ferrigno** [comment]
I cannot currently check JemX and Polar as the query gives an error

**Comment by ferrigno** [comment]
For JEM-X the default needs the source GX 5-1 to have one science window.

**Comment by ferrigno** [comment]
with these defaults,ISGRI has 2 science windows, JEM-X only one  (the current is none), SPI-ACS and Polar have a GRB

**Comment by ferrigno** [comment]
It sems to me that these defaults are OK

start_time='2017-03-06 13:26:48'
end_time='2017-03-06 15:32:27'
source='1E 1740.7-2942'
ra='265.97845833'
dec='-29.74516667'
osa_version='OSA11.1' (Also for ISGRI)

they correspond to selected_GRB = 'GRB170309A' visible in both SPI-ACS and Polar.

**Comment by ferrigno** [comment]
See https://gitlab.astro.unige.ch/oda/integral/oda-defaults in case

**Comment by volodymyrss** [comment]
alright, thanks a lot! I add this for implementation https://github.com/oda-hub/frontend-astrooda/issues/75
