### ISSUE TITLE
frontend expecting from antares data.file_name 

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-astrooda#46]

**Comment by dsavchenko** [comment]
The problem here really is that frontend expects data.file_name to be the list. In Antares response it is string. 

Actually, antares_spectra response is trying to imitate the response for the single image. 
Maybe I produce unconventional response?

**Comment by motame** [comment]
Fixed !
Indeed, the spectrum is displayed as an image and it is using the JS routine display_image() in the JS file astrooda.instrument.js.
Fot images, the field products.file_name returned by the dispatcher does contain three files (image. catalog and region files).
The JS function join is called to have only one parameter, file_list in the download URL.
While for the spectrum the field file_name does contain only one file.
The code has been updated to consider that situation :

`
    // Add button "Download" : download image, catalog and region file
    var file_name = data.file_name;
    if (Array.isArray(file_name)) file_name = file_name.join(',');
    url_params = {
      session_id: data.session_id,
      download_file_name: data.download_file_name,
      file_list: file_name,
      query_status: 'ready',
      job_id: job_id,
      instrument: instrument
    };
`
