### ISSUE TITLE
open page from help page

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/frontend-astrooda#49]
Links do not seem to work from the displayed help page

**Comment by motame** [comment]
The behavior has been generalized to all modals, i.e. each link or button opening a page in a modal (using the CSS class open-in-model) should have all its internal links opening in modal too. To keep the user within the same modal when clicking on any link in the modal until he/she closes it, all external links should open in a separate window/tab of the browser.
To summarize all internal links are opened in modals (the current one) and all external links open in a separate window/tab.

In addition to that, the main help page (help/astrooda) do have a kind of a simple breadcrumb, when the user clicks on an internal link, the opened page show  up with a breadcrumb in the header of the modal allowing the user to go back to the main help page  ... 
![link-to-home-01](https://user-images.githubusercontent.com/44972498/122637769-b6a61c00-d0f0-11eb-8129-2214b34e8bac.jpg)
