### ISSUE TITLE
Make installation-independent the paths of inserted images in pages  

### ISSUE THREAD

**Issue by motame** [oda-hub/frontend-astrooda#52]
Images inserted in pages (nodes) are inserted with an absolute path.
For example :  /cdci/astrooda/sites/default/files/Sign-in.png
The path is composed of the web site prefix "/cdci/astrooda", and the relative path to it "sites/default/files"
The problem come from the first part !
It makes all nodes dependent of that prefix and if the prefix changes all internal links will be broken.
That is exactly what is happening when moving to production with a different prefix.
I set-up already a solution to fix this issue consisting on using a variable storing the prefix to be used during installation of the module (core module astrooda or any other instrument module like Astrooda ISGRI, Astrooda Antares, etc.).
It's described on the wiki page [Astrooda: Description and installation](https://redmine.isdc.unige.ch/projects/integral-web-analysis/wiki/Description_and_installation), step 7 in section Installation steps.
But this procedure is not used at installation.

To avoid this procedure and have links totally independent of installation prefix, permanent path aliases have to be used for all images and any other link to be inserted in pages (nodes).

**Comment by ferrigno** [comment]
I used the functionality, upload image and then insert it without any manual intervention for the images. Let me know if I should do something different.

**Comment by motame** [comment]
Carlo, you did it in the right way !
But the path should be set differently by the system to make it independent of the web site prefix.
I am working on that !
There is a module that may help on that.

**Comment by volodymyrss** [comment]
I think this is done, all images shown, verified by @burnout87
