### ISSUE TITLE
The application name ? oda, astrooda, mmoda or ?

### ISSUE THREAD

**Issue by motame** [oda-hub/frontend-astrooda#53]
The system we are developing do have different names:
- ODA in dispatcher and back-end (data servers)
- Astrooda at front-end

This can lead to confusion or at least misunderstanding ...
As most of you know:
- ODA stands for Online Data Analysis
- Astrooda stands for Astro Online Data Analysis (two successives vowels for the fun as for the famous ERP [Odoo](https://www.odoo.com/))
The first one is too broad and the second one is an attempt to restrict the domain.

Now we introduced MMODA (Multi-Messenger Online Data Analysis)!
Shoud we stick now to this name ?
If yes I proceed with the change at the front-end side renaming the main module and all instrument modules.

**The name is quite important and it is may be time to decide for a final one and stick to it.**

Please make your comments and we let then the decisions-makers take an action ...

**Comment by volodymyrss** [comment]
We had [a meeting[(https://github.com/oda-hub/meetings/blob/main/2021-05-25/minutes.md#progress) preciesly about this, and decided on **mmoda** since it sounds similar to mmo that @andriineronov + develop in Paris. 
Shortened to oda when suitable, since easier to type.

Personally I do not think any name is final, since nothing here is, and it's not at all a bad thing to occasionally rebrand when context or organizational aspects change.

We can make another discussion if there is additional input.

**Comment by andriineronov** [comment]
Yes, I think we can try to be more consistent everywhere. MMODA everywhere sounds Ok. Perhaps we can think also to add a logo? How about this:
<img width="454" alt="MMODA_logo" src="https://user-images.githubusercontent.com/27765790/123245580-44b14680-d4e5-11eb-948e-dd7c0e8c8462.png">

**Comment by andriineronov** [comment]
... this follows the color scheme on GitHub pages for ODA

**Comment by volodymyrss** [comment]
I do not really like the shade on MM. Also it's a bit loaded, but probably ok. Apart from the shade I would be happy with it.

**Comment by andriineronov** [comment]
<img width="454" alt="MMODA_logo" src="https://user-images.githubusercontent.com/27765790/123246058-b1c4dc00-d4e5-11eb-9c39-01da4aeabfa9.png">

**Comment by ferrigno** [comment]
The last version is nice, maybe writing all the word "Online" in red? 
There should be a version without the full name for smaller icon, but I believe this is easy to be done.

Can you share somewhere the original file that you used to generate the pic?

**Comment by andriineronov** [comment]
[MMODA_logo.pptx](https://github.com/oda-hub/frontend-astrooda/files/6708845/MMODA_logo.pptx)
Here is the "original" file (not very advanced technology (:-))

**Comment by motame** [comment]
Excellent ! :+1:  :100: 
I start using it the name and the logo
We keep the issue open the time I change it at least in the front-end.

**Comment by motame** [comment]
Decided to be : MMODA
