### ISSUE TITLE
Antares Help page without images

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/frontend-astrooda#54]
http://cdcidev.mtmco.net/cdci/astrooda/help/antares

There are no images visible (at least for me).

![image](https://user-images.githubusercontent.com/2527219/123268646-84385c80-d4fe-11eb-974d-841dbee0e892.png)

**Comment by motame** [comment]
It's almost fixed !
All images are back except the second one.
I was not able to recover it ...

Following the issue #52, the way of inserting images in help pages has changed, improved ;-).
I will describe that in the corresponding issue.

Carlo, would you please send me the missing image and I will add it.

**Comment by ferrigno** [comment]
It was done by Andrii.

**Comment by motame** [comment]
OK, Andrii then :-) !

Andrii, would you please send me the missing image and I will add it (the second one in the page).

**Comment by andriineronov** [comment]
I cannot see the page now, but just in case, here are all images that I originally included in the help pages (in order):
<img width="637" alt="Antares1" src="https://user-images.githubusercontent.com/27765790/123440518-2aee2d00-d5d3-11eb-8d49-f7f4f253fcef.png">
<img width="602" alt="Antares2" src="https://user-images.githubusercontent.com/27765790/123440544-317ca480-d5d3-11eb-9baa-c2a0828ddb6d.png">
<img width="602" alt="Antares3" src="https://user-images.githubusercontent.com/27765790/123440555-34779500-d5d3-11eb-940d-d9427281001b.png">
<img width="419" alt="Antares4" src="https://user-images.githubusercontent.com/27765790/123440573-3b9ea300-d5d3-11eb-81c3-de15491e38aa.png">
<img width="398" alt="Antares5" src="https://user-images.githubusercontent.com/27765790/123440590-3f322a00-d5d3-11eb-87b2-dcb16f11577d.png">
<img width="641" alt="Antares6" src="https://user-images.githubusercontent.com/27765790/123440603-41948400-d5d3-11eb-8d08-a4d46176c450.png">

**Comment by motame** [comment]
:+1:

**Comment by motame** [comment]
Added ! but I am not sure if it's in the right place.
Andrii, would you please check and move to the right place if necessary.
