### ISSUE TITLE
change ISGRI OSA default to 10.2

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-astrooda#56]

**Comment by burnout87** [comment]
I remember having it changed to indeed `OSA11.0`. Here:

[https://github.com/oda-hub/frontend-astrooda/tree/f78975ea2dc955cbba85e1d6bc49588c58a18515](https://github.com/oda-hub/frontend-astrooda/tree/f78975ea2dc955cbba85e1d6bc49588c58a18515)

I will move it back to 'OSA 10.2`. Do we want the same behavior also for JEMX?

**Comment by burnout87** [comment]
> No, it needs to be 10.2 for ISGRI and 11.1 (actually; not 11.0) for jemx.

Is 11.0 anyway still available for  ISGRI ?

**Comment by burnout87** [comment]
> > > No, it needs to be 10.2 for ISGRI and 11.1 (actually; not 11.0) for jemx.
> > 
> > 
> > Is 11.0 anyway still available for ISGRI ?
> 
> no, let it be always 11.1

Sorry, then also for ISGRI?

**Comment by volodymyrss** [comment]
> > > > No, it needs to be 10.2 for ISGRI and 11.1 (actually; not 11.0) for jemx.
> > > 
> > > 
> > > Is 11.0 anyway still available for ISGRI ?
> > 
> > 
> > no, let it be always 11.1
> 
> Sorry, then also for ISGRI?

there are currently two versions supported both or ISGRI and JEMX: 10.2 and 11.1

default for ISGRI should be 10.2
default for JEMX should be 11.1

in the future, it should be easier to configure this and not hardcode. dispatcher knows of many more versions already.
