### ISSUE TITLE
progress bar not shown with second request

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-astrooda#58]
first  request shows new fancy and nice green progress bar.

but second request shows this:

![image](https://user-images.githubusercontent.com/3909535/124167588-78234080-daa4-11eb-8cdc-bb29e173da73.png)

confirmed on cdcidev

**Comment by volodymyrss** [comment]
this is really blocking since making many requests is a typical thing people do

**Comment by motame** [comment]
I'll fix it tomorrow morning.
I thought the throbber that was before is too small in a large window and replace it with the long bar but unfortunately it's not that nice.

**Comment by motame** [comment]
Fixed ! as well as the bug of the submit button becoming disabled after a close or an error.
Pushed to reference.

**Comment by volodymyrss** [comment]
Looks good, thanks!
