### ISSUE TITLE
need to sync images?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-astrooda#59]
images are not shown, since links like this one are not found:

https://frontend.staging.odahub.io/cdci/astrooda/sites/default/files/help/images/isgri-query.png

I notice in dev this exists:

.../mmoda/sites/default/files/help/images/isgri-query.png

so should I just import those files?
I tried for one and it works.

But I thought they would be handled differently somehow?

**Comment by motame** [comment]
My fault again !
I excluded in git all content files while I was supposed to make filtering : push content files and ignore system generated files.
It is done by now and I hope fixed.
Pushed to reference.

**Comment by volodymyrss** [comment]
yes, that does it. Thanks a lot for quick response!
