### ISSUE TITLE
Propose to change defaults

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/frontend-astrooda#62]
We might consider changing these defaults:

detection threshold 7 for both ISGRI and JEM-X, 

Maximum energy 20 keV for JEM-X.

minimum energy 28 keV for ISGRI  ONLY with OSA11

**Comment by burnout87** [comment]
> 
> Maximum energy 20 keV for JEM-X.

Apologies for the question, with minimum energy, you mean E1? and with maximum E2?

> 
> minimum energy 28 keV for ISGRI ONLY with OSA11

Also, do we want 20 for E1, only if Osa11.1 is selected? And what if OSA 10.2 is selected?

**Comment by ferrigno** [comment]
Like this for JEM-X
![image](https://user-images.githubusercontent.com/2527219/124453070-43a2d380-dd87-11eb-967d-b15c4afc32ca.png)

OSA 10.2 can stay as it is (20 keV)

**Comment by burnout87** [comment]
@motame I created a merge request on gitlab

Just one thing to be clarified: as of now, for the ISGRI instrument, in case the user changes the OSA version, the value for E1 is set to its default, do we want this behavior?

**Comment by burnout87** [comment]
As agreed with @ferrigno and @andriineronov , the ISGRI instrument is now set with with the minimum energy value to 20 keV and osa version do OSA 10.2.

Minimum energy value default value won't change with the osa version.

**Comment by volodymyrss** [comment]
is set where? Is there a PR?

**Comment by burnout87** [comment]
The changes were initially applied on gitlab, as we usually do with @motame and are already propagated here on github.

**Comment by volodymyrss** [comment]
Ok, is there a commit?

**Comment by burnout87** [comment]
[https://github.com/oda-hub/frontend-astrooda/tree/dc4d07ddd05d04059775ca11605be40144222052](https://github.com/oda-hub/frontend-astrooda/tree/dc4d07ddd05d04059775ca11605be40144222052)

**Comment by volodymyrss** [comment]
so this can be closed?

**Comment by burnout87** [comment]
If these applied defaults values are as expected, yes.

**Comment by volodymyrss** [comment]
the defaults are applied, if anyone else wants to check and revise please reopen.

The defaults, however, lead to failing default requests, I note here:

https://github.com/oda-hub/frontend-astrooda/issues/44
