### ISSUE TITLE
Not completely clear on where/how the default values are taken

### ISSUE THREAD

**Issue by burnout87** [oda-hub/frontend-astrooda#63]

**Comment by motame** [comment]
As commented in issue  #44 the instrument default values are defined in the file module_name.install.
For instance, ISGRI parameter default values of the module Astrooda_ISGRI are defined in astrooda_isgri.install
**This file is run only one time: at installation** and the default values are saved in the database at that time.
Any change after the installation is then not taken into account.
To make changes take effect a re-installation of the module is necessary and not only disabling/enabling the module.
Example:
```
drush dis -y astrooda_isgri
drush pmu -y astrooda_isgri
drush en -y astrooda_isgri
```
We can have an configuration page for each instrument to update its default values and other parameters.

See issue #68
