### ISSUE TITLE
Crashing when parsing error 

### ISSUE THREAD

**Issue by burnout87** [oda-hub/frontend-astrooda#65]

**Comment by burnout87** [comment]
A merge request on gitlab has been created

**Comment by burnout87** [comment]
I don't see the change deployed on the running instance. When will it be?

**Comment by volodymyrss** [comment]
> I don't see the change deployed on the running instance. When will it be?

you mean "staging" instance.

Please check now.

**Comment by burnout87** [comment]
> > I don't see the change deployed on the running instance. When will it be?
> 
> you mean "staging" instance.
> 
> Please check now.

Yes, thanks!
