### ISSUE TITLE
MMODA configuration pages

### ISSUE THREAD

**Issue by motame** [oda-hub/frontend-astrooda#68]
All configuration parameters of the application as well as the default parameters of instruments can be managed in some administration pages of Drupal.
I propose to have a main page for the core of the application (defined within the core module) and one page per instrument (defined within the instrument module).

**Comment by motame** [comment]
Gabrielle and Volodymyr, what is your opinion ?

**Comment by volodymyrss** [comment]
It would be a lot nicer, but to be clear, we are not going to change these values often.
So they will be adapted in dev instance, tested, and delivered within the database, like the help pages?

**Comment by motame** [comment]
I see your point !
They need to be tested on dev or preprod first !
Totally OK with the parallel you make with help pages.

If changed in prod, changes should be brought back to dev which could be fastidious !!!
It does not finally bring real added value.

**Comment by motame** [comment]
I should have a look in details to [Drupal 7 Installation Profile](https://www.drupal.org/docs/7/creating-distributions/how-to-write-a-drupal-7-installation-profile)
It may be useful for MMODA

**Comment by volodymyrss** [comment]
Yes, quite interesting.

**Comment by burnout87** [comment]
> I see your point !
> They need to be tested on dev or preprod first !
> Totally OK with the parallel you make with help pages.
> 
> If changed in prod, changes should be brought back to dev which could be fastidious !!!
> It does not finally bring real added value.

I share the same opinion, it is definitely useful but it might add confusion.

**Comment by motame** [comment]
Given the comments above, it can be closed i guess ?

**Comment by burnout87** [comment]
Yes I think so
