### ISSUE TITLE
Radius parameter for Antares not validated properly: should be 0.1 <= radius <= 2.5

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/frontend-astrooda#7]

**Comment by volodymyrss** [comment]
We can ask @motame of course, if he has time.
I would personally brave to attempt fixing it myself, if I have time. Or, @dsavchenko , how do you feel about some php+js? Small change like this should be easy to make.

**Comment by dsavchenko** [comment]
> how do you feel about some php+js?

I feel a bit scary :) 
But in fact it must be easy

**Comment by volodymyrss** [comment]
:)
what's the worst that can happen?..
