### ISSUE TITLE
Invalid OSA version in Frontend dropdown menu

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/frontend-astrooda#74]
2021.08.09T19:26:34 error 400, Bad Request, [ InstrumentQueryBackEnd : isgri ] constructor failed: ('value', 'OSA11.1', 'not allowed, allowed=', ['OSA11.0-dev1105', 'OSA11.0-dev201201', 'OSA10.2', 'OSA11.0-dev210203.1913-33455', 'OSA11.0-dev210306.2233-40322', 'OSA11.0-dev210308.2256-30192', 'OSA11.0', 'dev210205.1836-33694', 'OSA11.0-dev1208e1', 'OSA11.0-dev201208.2001-1265', 'OSA11.0-dev210205.1836-33694', 'OSA11.0-dev', 'OSA11.0-dev210802.1843-33499', 'OSA11.0-dev210805.1837-14880', 'OSA11.0-dev210807.2032-23305', 'OSA11.0-dev210808.0825-23947'])

**Comment by burnout87** [comment]
Could you post here the input you provided so the error can be reproduced?

**Comment by volodymyrss** [comment]
@ferrigno used frontend, as noted in the title. I take care of it.

**Comment by volodymyrss** [comment]
done.

**Comment by volodymyrss** [comment]
I let @ferrigno verify and close.

**Comment by ferrigno** [comment]
OK
