### ISSUE TITLE
set new and better defaults

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-astrooda#75]
```python
start_time='2017-03-06 13:26:48'
end_time='2017-03-06 15:32:27'
source='1E 1740.7-2942'
ra='265.97845833'
dec='-29.74516667'
osa_version='OSA11.1' # (Also for ISGRI)
```

**Comment by burnout87** [comment]
Values are now set

**Comment by volodymyrss** [comment]
ok! let us see them before final close of all related issues, which is the MR?

**Comment by burnout87** [comment]
> ok! let us see them before final close of all related issues, which is the MR?

This is the one:

[https://gitlab.astro.unige.ch/oda/frontend/astrooda/-/merge_requests/76](https://gitlab.astro.unige.ch/oda/frontend/astrooda/-/merge_requests/76)

**Comment by volodymyrss** [comment]
hm, and you checked it works for all instruments? I see jemx is osa10.2 strangely. after reinstall and cc.

**Comment by burnout87** [comment]
@ferrigno are the current default values ok?

**Comment by ferrigno** [comment]
Yes, defaults are good. I have seen that the MGIC tab does not work, though.

**Comment by volodymyrss** [comment]
> Yes, defaults are good. I have seen that the MGIC tab does not work, though.

MAGIC? we agreed to not include it, see [meeting](https://github.com/oda-hub/meetings/blob/main/2021-05-10/minutes.md)
