### ISSUE TITLE
add a note for account creation

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-astrooda#79]
something polite like "please use institutional address and explain a bit  your use case." (but more polite)

**Comment by burnout87** [comment]
A note could be:

```
Please use an institutional email address to sign up with the service.

In addition, we would like you to provide us with a small overview of your activities, in particular:

*  an estimation of the amount of resources needed
*  purpose of your work

```

Something else I might have forgotten?

**Comment by volodymyrss** [comment]
I would start like "We kindly ask you to use ...".

Otherwise it's ok. But let @ferrigno  see.

Where will be the description? There is no field on creation. Maybe we should add.

**Comment by burnout87** [comment]
> 
> Where will be the description? There is no field on creation. Maybe we should add.

It's what I was trying to understand too. I will have to ask @motame

**Comment by burnout87** [comment]
A first implementation :

![image](https://user-images.githubusercontent.com/3757833/132712974-0baa5cce-0d86-44da-8fc8-49e193912c1f.png)

**Comment by volodymyrss** [comment]
In essence - that's what we want. Thanks!
Could you make the second field larger? It will hold multiple sentences. Also we could put a limit on the size and mention it, like "maximum xxx characters please."
Also I am not sure about the second sentence, stylewise. It can be integrated in the first one.

**Comment by burnout87** [comment]
> Could you make the second field larger? It will hold multiple sentences.

That's exactly what I am trying to achieve.

> Also I am not sure about the second sentence, stylewise. It can be integrated in the first one.

I am still working on it, also I will the confirmation from @motame to confirm I followed the right procedure.

**Comment by volodymyrss** [comment]
> > Could you make the second field larger? It will hold multiple sentences.
> 
> That's exactly what I am trying to achieve.
> 
> > Also I am not sure about the second sentence, stylewise. It can be integrated in the first one.
> 
> I am still working on it, also I will the confirmation from @motame to confirm I followed the right procedure.

ok!

For the text, do make sure to coordinate with @ferrigno . It's he who qualifies use of the resource, on behalf.

**Comment by burnout87** [comment]
With some css adjustments:

![image](https://user-images.githubusercontent.com/3757833/132827010-34e5e883-56c5-44b0-ba89-a57d509e88d3.png)

**Comment by volodymyrss** [comment]
Nice! I would add some space before bold lines.
also "Please une" => "Please use"

**Comment by burnout87** [comment]
During today's call I forgot to confirm to @ferrigno regarding the notes in the registration form

**Comment by burnout87** [comment]
Here's an updated version @motame 
![image](https://user-images.githubusercontent.com/3757833/134137609-c1f6b8e3-d617-451d-8f45-b812204e2c12.png)

**Comment by motame** [comment]
@burnout87, as discussed, the Drupal core as well as contrib modules or themes should not be modified.
Practically speaking all the content of the component drupal7-for-astrooda is coming from outside.
The only changes that apply there are : update drupal core or install/update module as needed.

Then Drupal HOOKS should be used to implement the needed features in astrooda.
Add or update a field to user account can be done in astrooda in `.install`.
I suggest to add a new file astrooda.users.inc which should contain needed changes regarding user accounts.

**Comment by motame** [comment]
In fact, there is no need to code any thing except few css for of course the look and feel.
The field is now added in the user profile :
In addition to that a new module is installed : Field validation with other sub-modules allowing a lot of validation features like the min and max length of a field of type long text.

![chrome_cpurjfBZ44](https://user-images.githubusercontent.com/44972498/135440913-be91e9e2-72c2-44f2-9427-e2c3a9c33c2f.png)


![O7oen2MVei](https://user-images.githubusercontent.com/44972498/135441438-18bff30c-a35b-4b0d-babe-52c15438603b.png)

![FRbD0aNkY5](https://user-images.githubusercontent.com/44972498/135441584-23db251e-6501-4dd2-86ae-c7989794c5a2.png)

**Comment by motame** [comment]
Another enhancement brought by another module : [Maxlength](https://www.drupal.org/project/maxlength)

![vDwlQqZ7HD](https://user-images.githubusercontent.com/44972498/135443205-8046a8f3-4a95-47b7-8c84-32b45dbfdb60.png)

**Comment by burnout87** [comment]
Thanks! I am applying some css cosmetic improvements. Then it's ready!

**Comment by burnout87** [comment]
This is how it will look like:

![image](https://user-images.githubusercontent.com/3757833/135660708-33acffe6-1bee-40cb-9363-16bae39b4d3b.png)

**Comment by burnout87** [comment]
Here it is the (complete and final) version of the registration form. If we all agree with, then we can close this.

![image](https://user-images.githubusercontent.com/3757833/135813581-273f7424-7fcb-4aeb-b473-a190cf849b64.png)

**Comment by ferrigno** [comment]
No additional comments from me.

**Comment by burnout87** [comment]
Thanks

**Comment by motame** [comment]
Sorry ! I am disturbing a bit :-)
Do we need to set a minimum of characters or not, let say between 50 and 255 or ???

**Comment by volodymyrss** [comment]
@burnout87 can we verify and close?

**Comment by volodymyrss** [comment]
@burnout87  and @motame  confirm it's implemented

**Comment by burnout87** [comment]
I confirm there is a maximum length of 255
