### ISSUE TITLE
some ignored default frontend parameters are substituted after request by url

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-astrooda#82]
e.g. source name, which is never used by the dispatcher. Or time range in case when scw list is provided.

one way to deal with this is to always make sure that the parameters which are sent by frontend by default are always set

**Comment by burnout87** [comment]
The dispatcher workaround has been chosen, therefore this can be closed

**Comment by volodymyrss** [comment]
ok, fixed with https://github.com/oda-hub/dispatcher-app/pull/248.
