### ISSUE TITLE
provide sing-in button back? 

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-astrooda#88]
Actually, the button is already in help pages. Let us not change it now, and when we change it, we should change help at once. Inspecting on staging first.

Right now, it breaks vital user experience, as @ferrigno experienced.

I revert it and deploy immediately. Else it can be considered downtime - users are not able to access it (even if there is a workaround).

@motame argued for moving the button up by suggesting that big green buttons should not change on login. I am not necessarily sure this is a problem, and even if it is, it is still a problem since `API token` button in the the same block, and it changes.

**Comment by motame** [comment]
You are absolutely right and I am sorry for that.

In fact, the links related to the user are usually grouped in what is called "user menu":
Sign in, sign up, my account, log-out...

I thought that it would be nice to have it separated from the rest of links and moved to the top bar (the usual place for the user menu).
As in the future we will have a full site with a main menu at the top as it is now in CDCI web site, 

The user accounts may be used for other purposes in the project MMODA, not only for the current app but for others like mmoda gallery or ...

But if we decide to move it back as it was, it can be easily achieved.

**Comment by volodymyrss** [comment]
ok thanks! It's back and it's nicer than before. 

For the integration with gallery etc we have to see how it would be organized in the future.
