### ISSUE TITLE
Acknowledgement link should depend on instrument

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/frontend-astrooda#9]

**Comment by dsavchenko** [comment]
Duplicate of https://github.com/oda-hub/doc-review-guidelines/issues/9 
(with slightly broader scope)

**Comment by motame** [comment]
It's not really a duplicate as this is a feature request: each instrument should have its own paper quote while [the other one](https://github.com/oda-hub/doc-review-guidelines/issues/9) is specifying the paper to quote for ANTARES.

**Comment by motame** [comment]
Not only the link but the full acknowledgement text should be per instrument.

**Comment by motame** [comment]
Done and pushed in master.

**Comment by dsavchenko** [comment]
Thank you! I will close both issues
