### ISSUE TITLE
Separate password change from profile edit page

### ISSUE THREAD

**Issue by motame** [oda-hub/frontend-astrooda#91]
Editing a user profile is a bit annoying as it does include the two fields for password change.
It may usually happen that the need is to update another field rather than the password.
If both password fields are empty, the submit is accepted and the changes applied as expected.
However if one of the two fields is not empty - usually filled by the browser - the submit is rejected and the user need to empty both fields actively to allow the submit.
To avoid all this complexity, it would be better to move the change password to a separate page.
It will be replaced by a button landing on a page allowing that.

**Comment by motame** [comment]
Implemented !
As the user profile page does contain many tabs it is no more opened as a modal window (more complicated to implement) but it opens in a new browser tab/window

![firefox_DFX0Mq3TED](https://user-images.githubusercontent.com/44972498/150353626-c011edd9-6d0c-4672-ad66-7a6f864de44d.png)

Can be closed !

**Comment by volodymyrss** [comment]
ok!
