### ISSUE TITLE
API token button color

### ISSUE THREAD

**Issue by burnout87** [oda-hub/frontend-astrooda#93]
Is this intended ? Or just missing some css ?

![image](https://user-images.githubusercontent.com/3757833/136182414-e2ed539c-2949-44b7-8d24-85a27511eb09.png)

**Comment by motame** [comment]
Kept in place but color changed to green (btn-primary) as suggested.

![chrome_0wKg9Ww9iy](https://user-images.githubusercontent.com/44972498/150354456-f203ec74-245c-460f-9adc-f62eb7d255df.png)
