### ISSUE TITLE
need to use local resolver, else resolving may become unstable

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-astrooda#95]
apparently it happens and annoys users

**Comment by burnout87** [comment]
Regarding the setting of the `E1-keV` default value, I don't know why it is still applied like that, I though I had changed during the last review of the default values (I also noticed that it's the same for `E2-keV` and `detection_threshold`). 

It's fine for the sole purpose of the hotfix, but it is not right place.
